version: '1'
services:
  data-manipulation:
    container_name: data-manipulation
    build:
      context: data-manipulation
      dockerfile: Dockerfile
    image: data-manipulation:latest
    ports:
      - "8080:8080"
    depends_on:
      - PostgreSQL
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
  PostgreSQL:
    image: postgres
    volumes:
      - postgres_data:/var/lib`/postgresql/data_new
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
volumes:
  postgres_data:
    driver: local
