spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      org:
        hibernate:
          envers:
            store_data_at_delete: true
  liquibase:
    change-log: classpath:db.changelog/changelog.xml
    enabled: true